### ISSUE TITLE
Training Data Access

### ISSUE THREAD

**Issue by xu1110** [yt556677/ReFICR#1]
Hi, brilliant work! 
We are very interested in your work, and trying to run this code. But when we are trying to download the training dataset from the link provided in this repository, we find that due to permission issues, we are unable to access this resource. So could you please share the training dataset with us?
Thanks.

**Comment by yt556677** [comment]
Sorry for the late reply. You can access the folder now.

**Comment by xu1110** [comment]
Thanks for your help!
