### ISSUE TITLE
Question about instruction data construction

### ISSUE THREAD

**Issue by wxl1999** [yt556677/ReFICR#2]
Hi, brilliant work! I am very interested in it! 

When I read your paper and checked the instruction data, one thing I am very cautious about is that **how is the label for the ranking task constructed**? As we know, datasets like Redial and Inspired only provide item labels without their ranking and negative examples.

**Comment by yt556677** [comment]
Hi, thanks for your question! For the ranking task, given the candidate item set of ground truth and randomly sampled items, we create a ranked list based on the similarity between the item and the conversation context, the similarity between the item and the retrieved conversation context, and the similarity between the item and the ground truth. The candidate set in the ranking instruction is randomly ranked.

**Comment by wxl1999** [comment]
Thanks for your response! This is a feasible solution. I was wondering if you have tried other strategies for the construction of the ranking label.

**Comment by yt556677** [comment]
I have attempted to use more powerful models, such as GPT-3 and GPT-4, to construct the ranking labels. However, I have a limited number of tokens, so I could not complete the entire experiment.

**Comment by wxl1999** [comment]
Thanks for your response! Hope to see the model weight on Huggingface, I would like to test its excellent performance as soon as possible!

**Comment by wxl1999** [comment]
Hi, is the model ready for sharing on Huggingface?

**Comment by Aunnyxieyuzhou** [comment]
![image](https://github.com/user-attachments/assets/ff2916fe-83a6-4156-b43b-54c6a40745c3)
这是什么原因呀，如何解决呢

**Comment by yt556677** [comment]
Hi, you may find the model via https://huggingface.co/chujing007/ReFICR-qlora

**Comment by wxl1999** [comment]
Thanks for your great work!
